In [ ]:
import requests
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd

In [ ]:
#https://m2.ru/moskva/nedvizhimost/kupit-kvartiru/?districtIds=103&districtIds=81&districtIds=182&districtIds=218&districtIds=15&districtIds=60&districtIds=164&districtIds=37&districtIds={page_num}

In [ ]:

prices = np.array([], dtype = int)
area = np.array([], dtype = float)
rooms = np.array([])
floor = np.array([])
price_meters = np.array([], dtype = int)
districts = np.array([], dtype = str)
time = np.array([])
metro = np.array([])
seller = np.array([])

for page_num in range(1, 26):
    url = f"https://m2.ru/moskva/nedvizhimost/kupit-kvartiru/new/?districtIds=103&districtIds=81&districtIds=182&districtIds=218&districtIds=15&districtIds=60&districtIds=164&districtIds=37&districtIds=1&pageNumber={page_num}&sort=price_desc"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')

    for district_elem in soup.find_all('div', {'class': 'ClClickableAddress__links'}):
        addresses = district_elem.text.strip()
        district = addresses.split('\n')[0]
        districts = np.append(districts, district.replace('\xa0', '').replace('•', ',').replace(",", ".").replace('.', ',', 5).replace('до центра ', '').replace(' км', ''))

    #находим все элементы с ценами и добавляем их в список
    for price_elem in soup.find_all('span', {'itemprop': 'price'}):
        price = price_elem['content']
        prices = np.append(prices, int(price))

    for info_elem in soup.find_all('div', {'class': 'fonts-module__promo-subheader-alone___4BOzH fonts-module__bold___2Zct2'}):
        info = info_elem.text.strip().split(',')
        if len(info) == 4:
            info = ['.'.join(info[:2])] + info[2:]
        area = np.append(area, float(info[0].replace('\xa0м²', '')))
        rooms = np.append(rooms, (info[1].replace('-комн. квартира', '').strip()))
        floor = np.append(floor, (info[2].replace('\xa0этаж', '').strip()))

    for price_meter_elem in soup.find_all('div', {'class': 'color-primitives-module__black-400___re9Yh fonts-module__primary___2PNSt'}):
        price_meter_str = price_meter_elem.text.replace('&nbsp;', '').replace('₽/м²','')
        price_meters = np.append(price_meters, int(price_meter_str.replace('\xa0', '').replace(' ', '')))


    for time_elem in soup.find_all('div', {'class': 'colors-named-module__secondary___2WPH_ fonts-module__primary___2PNSt'}):
        timing = time_elem.text.strip()
        time = np.append(time, int(timing.replace(' мин.', '')))

    for seller_elem in soup.find_all('div', {'class': 'colors-named-module__secondary___2WPH_ fonts-module__small-alone___38xTq AuthorBadge__overflow'}):
        sellers = seller_elem.text.strip()
        seller = np.append(seller, (sellers.split())[0])


In [ ]:
prices
len(prices)

500

In [ ]:
area
len(area)

500

In [ ]:
rooms
len(rooms)

500

In [ ]:
rooms

array(['5', '4', '5', '5', '5', '4', '5', '5', '2', '3', '4', '5', '5',
       '5', '4', '4', '4', '4', '5', '5', '4', '4', '4', '6', '3', '3',
       '6', '5', '4', '5', '4', '5', '5', '1', '5', '6', '6', '3', '5',
       '3', '2', '4', '3', '4', '4', '6', '5', '4', '4', '4', '4', '4',
       '4', '4', '5', '4', '4', '6', '3', '5', '4', '5', '5', '4', '5',
       '4', '4', '3', '3', '6', '4', '2', '4', '3', '3', '5', '4', '4',
       '3', '5', '3', '3', '3', '4', '4', '3', '4', '4', '6', '3', '2',
       '3', '3', '3', '4', '6', '4', '3', '3', '3', '3', '3', '3', '2',
       '4', '2', '3', '3', '4', '6', '4', '3', '4', '4', '3', '3', '5',
       '3', '5', '2', '3', '2', '3', '3', '2', '2', '4', '4', '1', '6',
       '6', '4', '3', '3', '3', '4', '6', '3', '3', '2', '3', '4', '3',
       '1', '3', '2', '4', '4', '4', '4', '2', '4', '4', '3', '3', '4',
       '4', '4', '3', '3', '5', '2', '3', '4', '2', '2', '4', '4', '4',
       '3', '4', '4', '6', '2', '4', '4', '4', '3', '3', '2', '4

In [ ]:
rooms = np.where(rooms == 'студия', '0', rooms)
try:
  rooms = rooms.astype(np.int64)
except ValueError: pass

rooms

array(['5', '4', '5', '5', '5', '4', '5', '5', '2', '3', '4', '5', '5',
       '5', '4', '4', '4', '4', '5', '5', '4', '4', '4', '6', '3', '3',
       '6', '5', '4', '5', '4', '5', '5', '1', '5', '6', '6', '3', '5',
       '3', '2', '4', '3', '4', '4', '6', '5', '4', '4', '4', '4', '4',
       '4', '4', '5', '4', '4', '6', '3', '5', '4', '5', '5', '4', '5',
       '4', '4', '3', '3', '6', '4', '2', '4', '3', '3', '5', '4', '4',
       '3', '5', '3', '3', '3', '4', '4', '3', '4', '4', '6', '3', '2',
       '3', '3', '3', '4', '6', '4', '3', '3', '3', '3', '3', '3', '2',
       '4', '2', '3', '3', '4', '6', '4', '3', '4', '4', '3', '3', '5',
       '3', '5', '2', '3', '2', '3', '3', '2', '2', '4', '4', '1', '6',
       '6', '4', '3', '3', '3', '4', '6', '3', '3', '2', '3', '4', '3',
       '1', '3', '2', '4', '4', '4', '4', '2', '4', '4', '3', '3', '4',
       '4', '4', '3', '3', '5', '2', '3', '4', '2', '2', '4', '4', '4',
       '3', '4', '4', '6', '2', '4', '4', '4', '3', '3', '2', '4

In [ ]:
floor
len(floor)

500

In [ ]:
#https://m2.ru/moskva/nedvizhimost/kupit-kvartiru/new/?districtIds=103&districtIds=81&districtIds=182&districtIds=218&districtIds=15&districtIds=60&districtIds=164&districtIds=37&districtIds=1&pageNumber=2
#https://m2.ru/moskva/nedvizhimost/kupit-kvartiru/new/?districtIds=103&districtIds=81&districtIds=182&districtIds=218&districtIds=15&districtIds=60&districtIds=164&districtIds=37&districtIds=1
#https://m2.ru/moskva/nedvizhimost/kupit-kvartiru/new/?districtIds=103&districtIds=81&districtIds=182&districtIds=218&districtIds=15&districtIds=60&districtIds=164&districtIds=37&districtIds=1&pageNumber=3

In [ ]:
parts = np.char.partition(floor, '/')
floor_live = (parts[:, 0]).astype(np.int64)
display(floor_live)
floor_total = (parts[:, -1]).astype(np.int64)
display(floor_total)

array([ 7, 13,  1, 13,  1,  6,  1,  7,  1,  6,  1,  6,  6, 13, 13,  1,  1,
        5,  4,  1,  1, 21, 21,  1,  1,  5,  9, 10, 14,  6,  6, 21, 21,  5,
       12, 21, 21,  8,  5,  6, 14, 12,  5,  7, 12,  8,  5,  9, 21, 21, 11,
        4,  4,  6,  6,  8, 10,  2,  4,  5,  8, 21, 21,  9,  4,  6, 13,  5,
        5, 19,  5,  8, 12,  3,  2,  4,  5, 10,  6, 52, 12,  3,  3, 21, 21,
       12, 19, 19,  9,  6, 13,  3,  3, 11,  5,  9,  2,  5, 10,  4, 11,  9,
       10,  8,  4,  7,  4,  6,  5, 13,  4,  3, 20, 20,  3,  8, 52,  9,  6,
        6,  8,  7,  5,  3,  4,  4, 21, 21,  3,  8,  9, 30,  4,  8,  5, 16,
        8,  6,  9,  5,  2,  4,  4,  2,  6,  6, 20, 20, 20, 20,  5, 18, 18,
        4,  5, 21, 21,  3,  2,  3,  3,  7,  2,  4,  6,  4, 10, 21, 21,  7,
        9,  9,  8,  4, 10, 16, 10,  4,  4,  5, 10,  3,  4,  3, 13,  2, 13,
        6,  4,  3,  2, 19, 19, 17,  4,  5, 18, 18, 21,  3,  4,  4,  2,  1,
        3,  9,  9, 16, 16,  4, 21, 21,  3, 12,  2,  4, 15, 15,  9,  9, 12,
        8, 17, 17, 12,  2

array([ 8, 14,  3, 14,  3,  6,  3,  8,  3,  6,  3,  6,  6, 14, 14,  3,  3,
        5,  6,  2,  6, 21, 21,  2,  6,  5,  9, 14, 14,  8,  6, 21, 21,  5,
       14, 21, 21,  8,  8,  6, 14, 14,  5,  8, 14,  9,  6, 14, 21, 21, 14,
        6,  6,  8,  6, 14, 14,  6,  4,  6, 14, 21, 21, 14,  6, 14, 14,  6,
        6, 19,  8,  8, 14,  3,  6,  6, 14, 14,  6, 53, 14,  6,  6, 21, 21,
       14, 21, 21,  9,  6, 14,  6,  6, 14,  6,  9, 14,  6, 14,  8, 14, 14,
       14, 14, 14, 14, 14,  8,  6, 13, 14, 14, 21, 21,  8, 14, 53, 14,  6,
        8, 14, 14,  8, 14,  6,  6, 21, 21,  5,  9,  9, 32,  5, 14,  6, 18,
        9, 14, 14, 14,  8,  6,  8,  5,  6, 14, 21, 21, 21, 21,  8, 21, 21,
        6, 14, 21, 21,  6,  8,  6, 12, 14,  6,  7, 14,  8, 11, 21, 21, 14,
       13, 13,  9, 14, 10, 18, 10,  5, 14, 14, 10, 14,  5,  6, 13, 14, 18,
       14, 14,  5,  6, 21, 21, 18,  6, 14, 21, 21, 21,  6,  6,  6, 13,  5,
        6, 15, 15, 21, 21,  5, 21, 21,  5, 12,  6,  5, 21, 21, 15, 15, 18,
       15, 21, 21, 13, 14

In [ ]:
price_meters

array([4200588, 4516655, 2614921, 4976078, 2501532, 4997984, 2266586,
       3932630, 2634403, 4998082, 2309940, 3027792, 3076876, 4258923,
       4846511, 2439288, 2273944, 3562584, 2834958, 1954452, 1954452,
       1963500, 1963500, 1805496, 1805496, 3830771, 2500000, 3026488,
       3883821, 2967119, 2626265, 1870000, 1870000, 3242298, 3171768,
       1650000, 1650000, 4231865, 2653653, 2730218, 4165319, 3238748,
       3071233, 3040047, 3202983, 2000000, 2177208, 2936877, 1650000,
       1650000, 2948773, 2521490, 2521490, 2862628, 2709242, 2800387,
       2916776, 2192917, 3094767, 2158163, 2779771, 1551000, 1551000,
       2778675, 2012246, 2668553, 2715082, 3195907, 3195907, 1274149,
       2554372, 4460858, 2548880, 2521911, 2640921, 1894140, 2475655,
       2326318, 2811288,  987535, 2851478, 2215462, 2215462, 1850000,
       1850000, 2922724, 1472000, 1472000, 2500000, 2698162, 3309601,
       2170637, 2170637, 2796483, 2144054, 2000000, 1706865, 2497568,
       2598397, 2446

In [ ]:
districts

array(['Москва,ЦАО,Якиманка,Большой Толмачёвский переулок,5с5,В центре',
       'Москва,ЦАО,Якиманка,Большой Толмачёвский переулок,5с5,В центре',
       'Москва,ЦАО,Тверской район,улица Ильинка,3/8с3,В центре',
       'Москва,ЦАО,Якиманка,Большой Толмачёвский переулок,5с5,В центре',
       'Москва,ЦАО,Якиманка,Большой Толмачёвский переулок,5с5,В центре',
       'Москва,ЦАО,Тверской район,улица Большая Дмитровка,9с1,В центре',
       'Москва,ЦАО,Тверской район,улица Ильинка,3/8с3,В центре',
       'Москва,ЦАО,Якиманка,Большой Толмачёвский переулок,5с5,В центре',
       'Москва,ЦАО,Якиманка,Большой Толмачёвский переулок,5с5,В центре',
       'Москва,ЦАО,Тверской район,улица Большая Дмитровка,9с1,В центре',
       'Москва,ЦАО,Якиманка,Большой Толмачёвский переулок,5с5,В центре',
       'Москва,ЦАО,Басманный район,Потаповский переулок,5с4,В центре',
       'Москва,ЦАО,Басманный район,Потаповский переулок,5с4,В центре',
       'Москва,ЦАО,Якиманка,Большой Толмачёвский переулок,5с5,В центре'

In [ ]:
okrugi = np.array([i.split(',')[1] for i in districts])
okrugi

array(['ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО',
       'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО',
       'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО',
       'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО',
       'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО',
       'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО',
       'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО',
       'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЮАО', 'ЦАО', 'ЦАО',
       'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЗАО', 'ЦАО',
       'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО',
       'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО',
       'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО',
       'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЗАО',
       'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО', 'ЦАО',
       'ЦАО', 'ЦАО',

In [ ]:
raion = np.array([i.split(',')[2] for i in districts])
raion[raion == 'Судостроительная улица'] = 'Нагатино-Садовники' #почему то по этой улице в адресах нет района, пробил в гугле - это нагаитно садовники
raion
len(raion)

500

In [ ]:
rasstoyanie = np.array([(i.split(','))[-1] for i in districts])
rasstoyanie

array(['В центре', 'В центре', 'В центре', 'В центре', 'В центре',
       'В центре', 'В центре', 'В центре', 'В центре', 'В центре',
       'В центре', 'В центре', 'В центре', 'В центре', 'В центре',
       'В центре', 'В центре', 'В центре', 'В центре', 'В центре',
       'В центре', '4.2', '4.3', 'В центре', 'В центре', 'В центре',
       'В центре', 'В центре', 'В центре', 'В центре', 'В центре', '4.2',
       '4.3', 'В центре', 'В центре', '4.3', '4.3', 'В центре',
       'В центре', 'В центре', 'В центре', 'В центре', 'В центре',
       'В центре', 'В центре', 'В центре', 'В центре', 'В центре', '4.3',
       '4.3', 'В центре', 'В центре', 'В центре', 'В центре', 'В центре',
       'В центре', 'В центре', 'В центре', 'В центре', 'В центре',
       'В центре', '4.2', '4.3', 'В центре', 'В центре', 'В центре',
       'В центре', 'В центре', 'В центре', '4', 'В центре', 'В центре',
       'В центре', 'В центре', 'В центре', 'В центре', 'В центре',
       'В центре', 'В центре', '6.8

In [ ]:
def is_float(value): #https://stackoverflow.com/questions/354038/how-do-i-check-if-a-string-represents-a-number-float-or-int
    try:
        float(value)
        return True
    except ValueError:
        return False
v_is_float = np.vectorize(is_float)

#в процессе выяснилось, что есть корявые объявление, где нормальным образом не написано расстояние до центра,
#поэтому вызникали всякие странные значения по типу "25.13.8", которые я решил просто за NaNить

rasstoyanie = np.where(rasstoyanie == 'В центре', '0', rasstoyanie)
rasstoyanie[v_is_float(rasstoyanie)] = np.array(rasstoyanie[v_is_float(rasstoyanie)], dtype=np.float64)
rasstoyanie[~v_is_float(rasstoyanie)] = None
rasstoyanie

array(['0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '4.2', '4.3', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '0.0', '4.2', '4.3', '0.0', '0.0', '4.3',
       '4.3', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '4.3', '4.3', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '4.2', '4.3',
       '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '4.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '6.8', '0.0',
       '0.0', '0.0', '4.3', '4.3', '0.0', '4.3', '4.3', '0.0', '0.0',
       '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '0.0', '4.3', '4.3', '0.0', '0.0', '6.8',
       '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0',

In [ ]:
time

array([ 7.,  7.,  3.,  7.,  7.,  5.,  3.,  7.,  7.,  5.,  7.,  8.,  8.,
        7.,  7.,  7.,  7.,  3.,  5.,  6.,  6.,  7.,  9.,  6.,  6.,  3.,
        5.,  7.,  7.,  7.,  8.,  7.,  9.,  3.,  7.,  9.,  9.,  7.,  7.,
        8.,  7.,  7.,  3.,  7.,  7.,  5.,  8.,  7.,  8.,  9.,  7.,  6.,
        6.,  7.,  5.,  7.,  7.,  5.,  3.,  8.,  7.,  7.,  9.,  7.,  5.,
        7.,  7.,  6.,  6., 23.,  7.,  7.,  7.,  3.,  5.,  8.,  7.,  7.,
        5., 25.,  7.,  6.,  6.,  7.,  9.,  7.,  8.,  9.,  5.,  5.,  7.,
        6.,  6.,  7.,  8.,  5.,  7.,  5.,  7.,  7.,  7.,  7.,  7.,  7.,
        7.,  7.,  7.,  7.,  8., 10.,  7.,  7.,  7.,  9.,  7.,  7., 25.,
        7., 12.,  7.,  7.,  7.,  7.,  7.,  6.,  6.,  5.,  5.,  3.,  5.,
        5., 14.,  3.,  7.,  5., 17.,  5.,  7.,  7.,  7.,  7.,  8.,  7.,
        3.,  5.,  7.,  8.,  9.,  7.,  9.,  7.,  7.,  9.,  5.,  7.,  5.,
        5.,  8.,  7.,  8., 32.,  7.,  8., 15.,  7.,  7., 14.,  5.,  5.,
        7., 12., 12.,  5.,  7., 15., 19., 15.,  3.,  7.,  7., 15

In [ ]:
len(seller[seller=='Застройщик'])

476

In [ ]:
df = pd.DataFrame({'Price_Total': prices, 'Area': area, 'Price_Meter': price_meters, 'Rooms': rooms,
                   'Floor_Live': floor_live, 'Floor_Total': floor_total, 'Zone': okrugi, 'Neighborhood': raion, 'Distance': rasstoyanie,
                  'Time': time})
df.tail(20)

Price_Total   Area  Price_Meter Rooms  Floor_Live  Floor_Total  Zone  \
480    120640000  169.2       713002     3          14           14   ЗАО   
481    120570000  157.6       765038     4           9           21   ЦАО   
482    120420000  144.3       834511     4          10           23   ЦАО   
483    120363000   89.5      1344838     2          17           18   ЦАО   
484    120070000  161.6       743007     4           8           23   ЦАО   
485    119976240  151.6       791400     4           2            9  СЗАО   
486    119910000   49.7      2414619     0           2            4   ЦАО   
487    119897500  120.5       995000     2          19           21   ЦАО   
488    119897500  120.5       995000     2          19           21   ЦАО   
489    119410000  162.0       737099     4          13           21   ЦАО   
490    119410000  162.0       737099     4          13           21   ЦАО   
491    119240000  146.0       816712     4          15           23   ЦАО   
492    119100000  157.6       755711     4           8           21   ЦАО   
493    118949567  124.0       959271     2           8           13   ЦАО   
494    118917046  150.9       788052     4          28           32   ЮАО   
495    118827136  116.6      1018751     3           6           13   ЗАО   
496    118440000  157.6       751523     4           7           21   ЦАО   
497    118400000   45.6      2597631     0           1            5   ЦАО   
498    118180000  147.3       802308     4          11           21   ЦАО   
499    118170000  162.0       729444     4          12           21   ЦАО   

          Neighborhood Distance  Time  
480            Раменки      9.0  22.0  
481  Пресненский район      4.7  11.0  
482  Пресненский район      4.7  11.0  
483          Хамовники      3.0  14.0  
484  Пресненский район      4.8  11.0  
485  Хорошёво-Мнёвники     10.5   9.0  
486     Тверской район      0.0   3.0  
487  Пресненский район      4.2   7.0  
488  Пресненский район      4.3   9.0  
489  Пресненский район      4.6  11.0  
490  Пресненский район      4.6  11.0  
491  Пресненский район      4.7  11.0  
492  Пресненский район      4.7  11.0  
493              Арбат      0.0  10.0  
494  Даниловский район      0.0  11.0  
495       Дорогомилово      6.9  15.0  
496  Пресненский район      4.7  11.0  
497     Тверской район      0.0   3.0  
498  Пресненский район      4.6  11.0  
499  Пресненский район      4.6  11.0

In [ ]:
df.replace('nan', np.nan, inplace=True) #nan не распознавался как NaN, а распознавался как строка, хз почему...
df = df.dropna()

In [ ]:
df

Price_Total   Area  Price_Meter Rooms  Floor_Live  Floor_Total Zone  \
0     1929750000  459.4      4200588     5           7            8  ЦАО   
1     1884800000  417.3      4516655     4          13           14  ЦАО   
2     1777100000  679.6      2614921     5           1            3  ЦАО   
3     1753570000  352.4      4976078     5          13           14  ЦАО   
4     1649510000  659.4      2501532     5           1            3  ЦАО   
..           ...    ...          ...   ...         ...          ...  ...   
495    118827136  116.6      1018751     3           6           13  ЗАО   
496    118440000  157.6       751523     4           7           21  ЦАО   
497    118400000   45.6      2597631     0           1            5  ЦАО   
498    118180000  147.3       802308     4          11           21  ЦАО   
499    118170000  162.0       729444     4          12           21  ЦАО   

          Neighborhood Distance  Time  
0             Якиманка      0.0   7.0  
1             Якиманка      0.0   7.0  
2       Тверской район      0.0   3.0  
3             Якиманка      0.0   7.0  
4             Якиманка      0.0   7.0  
..                 ...      ...   ...  
495       Дорогомилово      6.9  15.0  
496  Пресненский район      4.7  11.0  
497     Тверской район      0.0   3.0  
498  Пресненский район      4.6  11.0  
499  Пресненский район      4.6  11.0  

[500 rows x 10 columns]

In [ ]:
df.to_csv('our_project.csv', index=False)
